### ISSUE TITLE
Use own API endpoint for datasource health extension

### ISSUE THREAD

**Issue by jezdez** [mozilla/redash-stmo#11]
@jasonthomas has opened https://github.com/mozilla/redash/issues/438 which basically means that the data source health extension is displayed in the admin since it's using the `/status.json` endpoint (which I didn't realized).

Since we can't really hook into the way the output from `/status.json` is automatically rendered on that page, we should instead move the datasource health extension to use an own API endpoint instead of point datadog (or whatever monitor it was using) to that new API endpoint.

While we're there, let's move all data source related things into a new subpackage, `redash_stmo/data_sources/`:

```
redash_stmo
└── data_sources
    ├── health.py
    ├── link
    │   ├── __init__.py
    │   └── bundle
    │       └── datasource_link.js
    └── version
        ├── __init__.py
        └── bundle
            └── datasource_version.js
```

**Comment by emtwo** [comment]
@jezdez I think it's still useful for `status.json` to show some data source health info since that is where ops usually look for it. I think we can do what jason suggested in https://github.com/mozilla/redash/issues/438 to show a basic state in `status.json` and perhaps the more detailed state in another endpoint.

**Comment by jezdez** [comment]
@emtwo That works for me 👍
