### ISSUE TITLE
Error running "make node_modules"

### ISSUE THREAD

**Issue by openjck** [mozilla/redash-stmo#40]
I've been following the instructions. `make build` and `make database` run successfully, but I get the following error when running `make node_modules`:

```
$ make node_modules
docker-compose run --rm server npm install
Starting redash-stmo_postgres_1 ... done
Starting redash-stmo_redis_1    ... done
Patching package.json...done.
/extension /app
Extras to install for deps 'all': {'.none', 'test', 'dev'}                                                I-flit.install
Installing requirements                                                                                   I-flit.install
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Symlinking redash_stmo -> /home/redash/.local/lib/python2.7/site-packages/redash_stmo                     I-flit.install
/app
Number of extension bundles found: 2
Copying "datasource_link" bundle to /app/client/app/extensions/datasource_link:
 - /home/redash/.local/lib/python2.7/site-packages/redash_stmo/data_sources/link/bundle/datasource_link.js -> /app/client/app/extensions/datasource_link/datasource_link.js
Copying "datasource_version" bundle to /app/client/app/extensions/datasource_version:
 - /home/redash/.local/lib/python2.7/site-packages/redash_stmo/data_sources/version/bundle/datasource_version.js -> /app/client/app/extensions/datasource_version/datasource_version.js
/extension/bin/docker-entrypoint: line 99: exec: npm: not found
make: *** [node_modules] Error 127
```

**Comment by openjck** [comment]
I think I understand what's happening: npm isn't available because the last stage of the build uses a Debian base, which does not include npm and does not have npm available in its default package repositories. There are blog posts which explain how to install npm on Debian ([example](https://linuxhint.com/install_npm_debian/)) and I'd be happy to do that, but I wanted to first check if this is the best approach. Is there another solution which would be preferred?

**Comment by jezdez** [comment]
Yeah, that's an oversight while upstream switched to the Debian image and we did a release. Sorry for the slow fix, this is all kinds of layers on top of each other 😬

**Comment by openjck** [comment]
I'm trying to learn more about Docker. How did this switch to Poetry fix the `npm` issue? I also see that *nodejs* is now installed with *apt-get*, but as far as I can tell, *npm* doesn't come bundled with *nodejs* on Debian.

Thanks again for getting this in. This turned out to be much more involved than I expected.

**Comment by openjck** [comment]
Oh, I see it now. You're adding the node package repository. 😃

**Comment by jezdez** [comment]
Hey no problem, the reason to switch from flit to poetry was only related to this issue, since the way how flit installed redash-stmo inside the Container could have led to an unclear state over multiple runs and confuse Redash's extension mechanism, basically failing to start the server because it thought that multipe versions of redash-stmo are installed. Poetry doesn't have that problem and handles installations of dependencies better as well. So a win-win in general.

As to the npm issue, I would prefer to use the [multi-stage Docker setup](https://docs.docker.com/develop/develop-images/multistage-build/) Redash uses to install Node modules (see multiple `FROM` commands in its [Dockerfile)](https://github.com/getredash/redash/blob/master/Dockerfile) as the first stage (and then [copying the resulting webpack bundle into the Python server container](https://github.com/getredash/redash/blob/27259b5abe4480d1112831952eb031560f546937/Dockerfile#L22)) but sadly this won't work for our inherited Docker environment since we don't want to build the Docker image on every change to a frontend extension file, but use the webpack devserver instead.

And since the last container specified in the Dockerfile is the one that is actually run (in multi-stage Docker setups) that means the redash-stmo repo is using that when inheriting from the mozilla/redash:rc Docker image. So we need to add Node/npm to the Python based container to retrofit the ability to install the npm modules. Phew!

**Comment by openjck** [comment]
That's very helpful. I had considered adding an additional stage for Node to solve this problem, but as you say, that woudln't have worked very well. Thank you for explaining that for me. :smiley:
